apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: branch-planner-token
  namespace: flux-system
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: branch-planner-token/credential
