apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - routes.yaml
  - secrets.yaml

