---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shlink-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: shlink-api
      remoteRef:
        key: shlink-api
        property: credential