apiVersion: v1
kind: Service
metadata:
  name: shlink
  labels:
    app: shlink
spec:
  type: ClusterIP
  selector:
    app: shlink
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink-cloudflare
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: shlink.vaughn.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shlink
            port:
              number: 80
