---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: operators
spec:
  interval: 5m0s
  url: https://github.com/adyanth/cloudflare-operator
  ref:
    tag: v0.13.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: operators
spec:
  interval: 3m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
  path: config/default
  prune: true