apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homarr
  namespace: applications
spec:
  interval: 24h
  url: https://homarr-labs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: homarr
      version: "8.6.0"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: applications
      interval: 12h
  values:
    database:
      type: postgresql

    envSecrets:
      dbCredentials:
        existingSecret: db-secret
        dbUrlKey: db-url
      dbEncryption:
        existingSecret: db-encryption
        key: db-encryption-key

    persistence:
      config:
        enabled: true
        size: 1Gi
      data:
        enabled: true
        size: 2Gi
      icons:
        enabled: true
        size: 1Gi

    service:
      type: ClusterIP
      port: 3000
