apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-encryption
  namespace: applications
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: db-encryption
    creationPolicy: Owner
    template:
      data:
        db-encryption-key: "{{`{{ .encryptionKey }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator