---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-encryption
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: encryption-key
      remoteRef:
        key: homarr-encryption
        property: credential