opensearch:
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: local-issuer
    ingressClassName: cilium
    path: /
    hosts:
      - opensearch.apicius.local
#    tls:
#      - secretName: chart-example-tls
#        hosts:
#          - chart-example.local
opensearch-dashboards:
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"