opensearch:
  masterService: "opensearch-cluster-master"
  roles:
  - master
  - ingest
  - data
  - remote_cluster_client
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  # Allows you to add any config files in {{ .Values.opensearchHome }}/config
  opensearchHome: /usr/share/opensearch
  # such as opensearch.yml and log4j2.properties
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster

      # Bind to all interfaces because we don't know what IP address Docker will assign to us.
      network.host: 0.0.0.0

      # # minimum_master_nodes need to be explicitly set when bound on a public IP
      # # set to 1 to allow single node clusters
      # discovery.zen.minimum_master_nodes: 1

      # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
      #discovery.type: single-node

      plugins:
        security:
          nodes_dn:
             - 'CN=opensearch.apicius.local'
          ssl:
            transport:
              pemcert_filepath: certs/tls.crt
              pemkey_filepath: certs/tls.key
              pemtrustedcas_filepath: certs/ca.crt
              enforce_hostname_verification: false
            http:
              enabled: false
          allow_unsafe_democertificates: false
          allow_default_init_securityindex: true
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
        authc:
          openid_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: openid
              challenge: false
              config:
                subject_key: preferred_username
                roles_key: roles
                openid_connect_url: https://auth.vaughn.sh/.well-known/openid-configuration
            authentication_backend:
              type: noop
  secretMounts:
    - name: opensearch-certs
      secretName: tls-for-opensearch-key-pair
      path: /usr/share/opensearch/config/certs
opensearch-dashboards:
  opensearchHosts: "http://opensearch-cluster-master:9200"
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"