opensearch:
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "false"
opensearch-dashboards:
  extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "<path:kv/data/opensearch/admin-password#value>"