---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: restic-password
      remoteRef:
        key: minecraft-restic
        property: credential
    - secretKey: restic-repository
      remoteRef:
        key: minecraft-restic
        property: username
    - secretKey: aws-access-key-id
      remoteRef:
        key: minecraft-minio-role
        property: username
    - secretKey: aws-secret-access-key
      remoteRef:
        key: minecraft-minio-role
        property: credential
    - secretKey: rcon-password
      remoteRef:
        key: minecraft-rcon-password
        property: password