---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: restic-password
      remoteRef:
        key: minecraft-restic/credential
    - secretKey: restic-repository
      remoteRef:
        key: minecraft-restic/username
    - secretKey: aws-access-key-id
      remoteRef:
        key: minecraft-minio-role/username
    - secretKey: aws-secret-access-key
      remoteRef:
        key: minecraft-minio-role/credential
    - secretKey: rcon-password
      remoteRef:
        key: minecraft-rcon-password/password