---
apiVersion: v1
kind: Service
metadata:
  name: bluemap
spec:
  selector:
    app: minecraft-sexybabeycraft
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluemap-cloudflare
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: maps.vaughn.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bluemap
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluemap-tailscale
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: bluemap
      port:
        number: 80
