apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: discsync
  namespace: applications
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/vaughnw128/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discsync
  namespace: applications
spec:
  interval: 5m
  releaseName: discsync
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: discsync
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: discsync
      interval: 5m
  values:
    secretVars:
      DISCORD_TOKEN: "discsync-discord-token/credential"

    envVars:
      DATABASE_URL: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@grove-cluster-rw.applications.svc.cluster.local:5432/sbux-oracle"

    db:
      enabled: true
      name: "sbux-oracle"
      cluster: "grove-cluster"

      migrator:
        secretName: "pg-migrator"

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 2048Mi
        cpu: 1024m