democratic-csi:
  csiDriver:
    name: "org.democratic-csi.nfs"

  storageClasses:
  - name: truenas-nfs-csi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs

    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    config:
      driver: freenas-api-nfs
      instance_id:
      httpConnection:
        protocol: https
        port: 443
        allowInsecure: true
      zfs:
        datasetParentName: pool/k8s/nfs/v
        detachedSnapshotsDatasetParentName: pool/k8s/nfs/s
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: 0
        datasetPermissionsGroup: 0
      nfs:
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""

