    ipam:
        mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
        capabilities:
            ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
            cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
    cgroup:
        autoMount:
            enabled: false
        hostRoot: "/sys/fs/cgroup"
    k8sServiceHost: localhost
    devices:
        - eth0
    k8sServicePort: 7445
    gatewayAPI:
        enabled: true
        enableAlpn: true
        enableAppProtocol: true
        secretsNamespace:
          sync: true
    l2announcements:
        enabled: true
    ingressController:
        enabled: true
        default: true
        loadbalancerMode: shared
        enforceHttps: false
    envoy:
        enabled: true
    hubble:
        peerService:
            clusterDomain: cluster.local
        relay:
            enabled: true
        ui:
            enabled: true
        tls:
            auto:
              enabled: true
              method: helm
              certValidityDuration: 2000
        metrics:
            enableOpenMetrics: true
            enabled:
            - dns,
            - drop,
            - tcp,
            - flow,
            - port-distribution,
            - icmp,
            - httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true