apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trivy
  namespace: operators
spec:
  interval: 24h
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: operators
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: trivy-operator
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: trivy
        namespace: operators
      interval: 12h