# It is assumed that kube-system, flux-system, and default will be created automatically
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: controllers
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: applications