apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "default-mtls"
spec:
  description: "Force mTLS everywhere!"
  endpointSelector: {}
  ingress:
    - authentication:
        mode: required
  egress:
    - authentication:
        mode: required