apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litellm
  namespace: applications
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/berriai
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: applications
spec:
  interval: 5m
  releaseName: litellm
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: litellm-helm
      version: "0.1.825"
      sourceRef:
        kind: HelmRepository
        name: litellm
      interval: 5m
  values:
    masterkeySecretName: "litellm-secrets"
    masterkeySecretKey: "master-key"
    proxyConfigMap:
      create: true
    proxy_config:
      model_list:
        - model_name: text-embedding-qwen3-embedding-0.6b
          litellm_params:
            model: openai/text-embedding-qwen3-embedding-0.6b
            api_key: "n/a"
            api_base: http://localai-local-ai.applications.svc.cluster.local:80/v1
      general_settings:
        master_key: os.environ/PROXY_MASTER_KEY
