apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crosstown-traffic
  namespace: crosstown-traffic
spec:
  interval: 24h
  url: https://github.com/vaughnw128/crosstown-traffic/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crosstown-traffic
  namespace: crosstown-traffic
spec:
  interval: 30m
  chart:
    spec:
      chart: crosstown-traffic
      version: "0.3.16"
      sourceRef:
        kind: HelmRepository
        name: crosstown-traffic
        namespace: crosstown-traffic
      interval: 12h
