apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - benbot
  - crosstown-traffic
  - databases
  - discsync
  - discsync-embeddings
  - discsync-postgrest
  - jellyfin
  - localai
  - mc-status-rs
  - minecraft
  - open-webui
  - qdrant
  - sexybabeycord
  - uptime-kuma
  - whoami
