apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: applicaitons
spec:
  interval: 24h
  url: https://helm.irsigler.cloud
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: applicaitons
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: uptime-kuma
      version: "2.21.3"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: applications
      interval: 12h