kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma-pvc
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"