---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: imgproxy-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: imgproxy-secrets
    template:
      engineVersion: v2
  data:
    - secretKey: IMGPROXY_KEY
      remoteRef:
        key: imgproxy-url-signing
        property: key
    - secretKey: IMGPROXY_SALT
      remoteRef:
        key: imgproxy-url-signing
        property: salt
