apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: imgproxy-tunnel
  labels:
    cfargotunnel.com/kind: TunnelBinding
    cfargotunnel.com/name: cluster-tunnel
subjects:
  - name: imgproxy
    spec:
      fqdn: imgproxy.vaughn.sh
      protocol: http
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
