apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imgproxy-cloudflare
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: imgproxy.vaughn.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imgproxy-service
            port:
              number: 80
