apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nessie
  namespace: applications
spec:
  interval: 24h
  url: https://charts.projectnessie.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nessie
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: nessie
      version: "0.104.3"
      sourceRef:
        kind: HelmRepository
        name: nessie
        namespace: applications
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 19120
    catalog:
      enabled: true
      iceberg:
        defaultWarehouse: iceberg
        warehouses:
        - name: iceberg
          location: s3://iceberg
        objectStoresHealthCheckEnabled: true
      storage:
        s3:
          defaultOptions:
            region: us-east-1
            endpoint: https://iceberg.internal.vw-ops.net
            pathStyleAccess: "true"
            accessKeySecret:
              name: iceberg-svc
              awsAccessKeyId: username
              awsSecretAccessKey: password
