apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: controllers
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: cert-manager
      version: "v1.18.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: controllers
      interval: 12h
  values:
    extraArgs:
        - "--enable-gateway-api"
    installCRDs: true