apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: controllers
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: controllers
      interval: 12h
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
    - name: truenas-nfs
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs

      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    driver:
      config:
        driver: freenas-api-nfs
      existingConfigSecret: democratic-csi-config

