apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: controllers
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: controllers
      interval: 12h
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
    storageClasses:
    - name: truenas-nfs
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    controller:
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
          pullPolicy: Always
        extraEnv:
          - name: TRUENAS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: truenas-api-key
                key: truenas-api-key
    node:
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
          pullPolicy: Always
    driver:
      config:
        driver: freenas-api-nfs
        httpConnection:
          protocol: https
          port: 443
          allowInsecure: true
          host: 10.0.0.3
          apiKey: "${TRUENAS_API_TOKEN}"
        zfs:
          datasetParentName: pool/k8s/nfs/v
          detachedSnapshotsDatasetParentName: pool/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.0.0.3
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""