---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: 1password-sdk
  data:
    - secretKey: truenas-api-key
      remoteRef:
        key: truenas-api-key/credential