apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  target:
    name: democratic-csi-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver:
            config:
              driver: freenas-api-nfs
              instance_id:
              httpConnection:
                protocol: https
                port: 443
                allowInsecure: true
                host: "http://roke.apicius.local"
                apiKey: "{{ .truenas-api-key }}"
              zfs:
                datasetParentName: pool/k8s/nfs/v
                detachedSnapshotsDatasetParentName: pool/k8s/nfs/s
                datasetEnableQuotas: true
                datasetEnableReservation: false
                datasetPermissionsMode: "0777"
                datasetPermissionsUser: 0
                datasetPermissionsGroup: 0
              nfs:
                shareHost: "roke.apicius.local"
                shareAlldirs: false
                shareAllowedHosts: []
                shareAllowedNetworks: []
                shareMaprootUser: root
                shareMaprootGroup: root
                shareMapallUser: ""
                shareMapallGroup: ""

  data:
  - secretKey: truenas-api-key
    remoteRef:
      key: truenas-api-key/credential