apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reflector
  namespace: controllers
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: controllers
      interval: 12h