---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-postgres
  namespace: security
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: postgresql
      version: "15.2.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-postgres
        namespace: security
      interval: 12h
  values:
    passwordUpdateJob:
      enabled: true
    auth:
      existingSecret: siem-nessie-pg
      database: nessie
    primary:
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 8Gi
        accessModes:
          - ReadWriteOnce
