apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: siem-nessie-pg
  namespace: security
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: username
      remoteRef:
        key: siem-nessie-pg
        property: username
    - secretKey: password
      remoteRef:
        key: siem-nessie-pg
        property: password
    - secretKey: postgresql-password
      remoteRef:
        key: siem-nessie-pg
        property: password
    - secretKey: replication-password
      remoteRef:
        key: siem-nessie-pg
        property: password

