apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-api-key
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: key
    remoteRef:
      key: unifi-external-dns
      property: credential
