apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iceberg-user
  namespace: security
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: username
      remoteRef:
        key: iceberg-user
        property: username
    - secretKey: password
      remoteRef:
        key: iceberg-user
        property: password 
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iceberg-root-user
  namespace: security
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: iceberg-root-user
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: iceberg-root-user
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: iceberg-root-user
        property: password 
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iceberg-svc
  namespace: security
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: iceberg-svc
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: iceberg-svc
        property: username
    - secretKey: password
      remoteRef:
        key: iceberg-svc
        property: password 