apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fission
  namespace: applicaitons
spec:
  interval: 24h
  url: https://fission.github.io/fission-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fission
  namespace: applicaitons
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: fission
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: fission
        namespace: applicaitons
      interval: 12h