apiVersion: v2
name: cilium
description: Cilium helm chart for terraformed Talos
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: cilium
  version: "1.17.1"
  repository: "https://helm.cilium.io/"
