apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-receiver-token
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: github-webhook-receiver/credential
