apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-operator
  namespace: operators
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: operators
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: tailscale-operator
      version: "1.84.2"
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: operators
      interval: 12h