---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: operators
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-operator-oauth
        property: username
    - secretKey: client_secret
      remoteRef:
        key: tailscale-operator-oauth
        property: credential