apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grove-cluster
  namespace: applications
spec:
  instances: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  storage:
    size: 32Gi
  enableSuperuserAccess: true
  managed:
    roles:
      - name: open-webui-app
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: open-webui-pg-app
      - name: sbux-oracle-app
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: sbux-oracle-pg-app
