apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 24h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: base
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: istiod
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: cni
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: ztunnel
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: istio-ingress
#  namespace: istio-system
#spec:
#  interval: 30m
#  chart:
#    spec:
#      reconcileStrategy: Revision
#      chart: gateway
#      version: "1.26.2"
#      sourceRef:
#        kind: HelmRepository
#        name: istio
#        namespace: istio-system
#      interval: 12h