apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
  namespace: controllers
spec:
  interval: 5m0s
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: controllers
spec:
  interval: 5m
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: reloader
      interval: 5m
