---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anki-stack-generated
  namespace: applications
spec:
  refreshPolicy: CreatedOnce
  target:
    name: anki-stack-generated
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        sync-username: "anki"
        sync-password: "{{ .sync_password }}"
        sync-user1: "anki:{{ .sync_password }}"
        ankiconnect-api-key: "{{ .api_key }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator
      rewrite:
        - regexp:
            source: "^password$"
            target: "sync_password"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator
      rewrite:
        - regexp:
            source: "^password$"
            target: "api_key"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: anki-stack-push
  namespace: applications
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: anki-stack-generated
  data:
    - match:
        secretKey: sync-username
        remoteRef:
          remoteKey: anki-sync
          property: username
    - match:
        secretKey: sync-password
        remoteRef:
          remoteKey: anki-sync
          property: password
    - match:
        secretKey: sync-user1
        remoteRef:
          remoteKey: anki-sync
          property: credential
    - match:
        secretKey: ankiconnect-api-key
        remoteRef:
          remoteKey: anki-connect
          property: api-key
