apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trino-gateway
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: trino-gateway
      version: "1.15.3"
      sourceRef:
        kind: HelmRepository
        name: trino-gateway
        namespace: applications
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 8080 