apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trino
  namespace: applications
spec:
  interval: 24h
  url: https://trinodb.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trino
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: trino
      version: "1.40.0"
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: applications
      interval: 12h
  values:
    server:
      workers: 3
      node:
        environment: "production"
    service:
      type: ClusterIP
      port: 8080 
    additionalConfigProperties:
     - http-server.process-forwarded=true
    catalogs:
      iceberg: |-
        connector.name=iceberg
        iceberg.catalog.type=nessie
        iceberg.nessie-catalog.uri=https://nessie.internal.vw-ops.net/api/v2
        iceberg.nessie-catalog.ref=main
        iceberg.nessie-catalog.default-warehouse-dir=s3://iceberg
        
        fs.native-s3.enabled=true
        s3.aws-access-key=${ENV:MINIO_USER}
        s3.aws-secret-key=${ENV:MINIO_PASSWORD}
        s3.endpoint=https://iceberg.internal.vw-ops.net
        s3.path-style-access=true
        s3.region=us-east-1
    env:
      - name: MINIO_USER
        valueFrom:
          secretKeyRef:
            name: iceberg-svc
            key: username
      - name: MINIO_PASSWORD
        valueFrom:
          secretKeyRef:
            name: iceberg-svc
            key: password