apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flux-operator
      version: "0.33.0"
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
      interval: 12h