---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: qdrant
  namespace: applications
spec:
  interval: 24h
  url: https://qdrant.github.io/qdrant-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: qdrant
      version: "1.15.5"
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: applications
      interval: 12h

