apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: applications
spec:
  interval: 24h
  url: https://goauthentik.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: authentik
      version: "2025.10.1"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: applications
      interval: 12h
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret

    authentik:
      log_level: info
      postgresql:
        host: grove-cluster-rw.applications.svc.cluster.local
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password

    server:
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-pg-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true

    worker:
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-pg-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true

    # lazy
    redis:
      enabled: true