apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-app
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: authentik-pg-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "authentik-app"
        password: "{{`{{ .password }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator