apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-pg-app
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: homarr-pg-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "homarr-app"
        password: "{{`{{ .password }}`}}"
        uri: "postgresql://homarr-app:{{`{{ .password }}`}}@grove-cluster-rw.applications.svc.cluster.local:5432/homarr"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator