apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - grove-cluster.yaml
  - sbux-oracle-db.yaml
  - pg-migrator-secret.yaml
  - service-lb.yaml
  - homarr-app.yaml
  - homarr-db.yaml
  - homarr-app-pushsecret.yaml
  - open-webui-app.yaml
  - open-webui-db.yaml
  - open-webui-app-pushsecret.yaml
