apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-pg-app
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: open-webui-pg-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "open-webui-app"
        password: "{{ .password }}"
        uri: "postgresql://open-webui-app:{{ .password }}@grove-cluster-rw.applications.svc.cluster.local:5432/open-webui"
  data:
    - secretKey: password
      remoteRef:
        key: open-webui-pg-app
        property: password
