---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-operator-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-operator-api-token/credential
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: cloudflare-operator-api-key/credential