apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: applications
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: applications
      interval: 12h
  values:
    config:
      pluginsDir: /build/plugins
      initContainers:
        - command:
            - /bin/sh
            - -c
            - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
          image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
          imagePullPolicy: Always
          name: headlamp-plugins
          volumeMounts:
            - mountPath: /build/plugins
              name: headlamp-plugins
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        enabled: true
        size: 1Gi
      volumeMounts:
        - mountPath: /build/plugins
          name: headlamp-plugins
      volumes:
        - name: headlamp-plugins
          persistentVolumeClaim:
            claimName: headlamp