apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: applications
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: applications
      interval: 12h