apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sexybabeycord
  namespace: applications
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/vaughnw128/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sexybabeycord
  namespace: applications
spec:
  interval: 5m
  releaseName: sexybabeycord
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: sexybabeycord
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: sexybabeycord
      valuesFiles:
        - "values.yaml"
      interval: 5m