single-container:
  name: mc-status-rs
  image: "ghcr.io/vaughnw128/mc-status-rs:v0.1.19"
  size: micro
  vaultSecrets:
    - name: "DISCORD_TOKEN"
      path: "mc-status-rs/discord-token"
  env:
    - name: "MAPS_ADDRESS"
      value: "https://maps.vaughn.sh"
    - name: "MC_SERVER_IP"
      value: "mc.vaughn.sh"
