apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discsync-pg-app
spec:
  refreshInterval: "24h"
  target:
    name: discsync-pg-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "discsync-app"
        password: "{{ .password }}"
        uri: "postgresql://discsync-app:{{ .password | urlquery }}@grove-cluster-rw.applications.svc.cluster.local:5432/discsync"
        uri-pooler-rw: "postgresql://discsync-app:{{ .password | urlquery }}@grove-cluster-pooler-rw.applications.svc.cluster.local:5432/discsync"
        uri-pooler-rw-lb: "postgresql://discsync-app:{{ .password | urlquery }}@grove-cluster-pooler-rw.internal.vw-ops.net:5432/discsync"
        uri-pooler-ro: "postgresql://discsync-app:{{ .password | urlquery }}@grove-cluster-pooler-ro.applications.svc.cluster.local:5432/discsync"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator
