apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: discsync-pg-app-push
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: discsync-pg-app
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: discsync-pg-app
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: discsync-pg-app
          property: password
    - match:
        secretKey: uri
        remoteRef:
          remoteKey: discsync-pg-app
          property: uri
    - match:
        secretKey: uri-pooler-rw
        remoteRef:
          remoteKey: discsync-pg-app
          property: uri-pooler-rw
    - match:
        secretKey: uri-pooler-rw-lb
        remoteRef:
          remoteKey: discsync-pg-app
          property: uri-pooler-rw-lb
    - match:
        secretKey: uri-pooler-ro
        remoteRef:
          remoteKey: discsync-pg-app
          property: uri-pooler-ro
