apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: operators
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: operators
spec:
  interval: 60m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: external-secrets
      version: "0.18.1"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: operators
      interval: 12h