apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: applications
spec:
  interval: 24h
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: applications
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: minio
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: applications
      interval: 12h
  values:
    mode: standalone
    persistence:
      enabled: true
      size: 100Gi
      storageClass: "truenas-nfs"
    buckets:
      - name: iceberg
        policy: none
        purge: false
    existingSecret: "iceberg-root-user"
    # users:
    #   - accessKey: iceberg-svc
    #     existingSecret: "iceberg-user"
    #     existingSecretKey: "password"
    #     policy: iceberg-readwrite
    # svcaccts:
    #   - accessKey: RWyPPR23cDIuJRdvkLqx
    #     existingSecret: "iceberg-user"
    #     existingSecretKey: "password"
    #     user: iceberg-svc
    policies:
      - name: iceberg-readwrite
        statements:
          - effect: Allow
            actions:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
            resources:
              - "arn:aws:s3:::iceberg"
          - effect: Allow
            actions:
              - s3:AbortMultipartUpload
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListMultipartUploadParts
              - s3:PutObject
            resources:
              - "arn:aws:s3:::iceberg/*"
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      type: ClusterIP
      port: 9001
    region: us-east-1
    resources:
      requests:
        memory: 512Mi
        cpu: 500m 