apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-api-key
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: truenas-api-key
    remoteRef:
      key: truenas-api-key
      property: credential
