{{ if .Values.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: {{ .Values.gateway.hostname }}
  listeners:
  - protocol: HTTP
    hostname: {{ .Values.gateway.hostname }}
    port: 80
    name: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-route
spec:
  parentRefs:
  - name: http-gateway
    namespace: bento
  hostnames:
  - {{ .Values.gateway.hostname | quote}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: bento-bento-stream
      port: 80

{{ end }}