apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: atlantis
  namespace: operators
spec:
  interval: 24h
  url: https://runatlantis.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: operators
spec:
  interval: 60m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: atlantis
      version: "5.17.2"
      sourceRef:
        kind: HelmRepository
        name: atlantis
        namespace: operators
      interval: 12h
  values:
    loadEnvFromSecrets:
      - atlantis-gh-secret
    orgAllowlist: github.com/vaughnw128/*
    webhook_ingress:
      enabled: true
      ingressClassName: cloudflare-tunnel
      path: /*
      pathType: ImplementationSpecific
      host: "atlantis.vaughn.sh"
    environment:
      ATLANTIS_WRITE_GIT_CREDS: true
    service:
      type: ClusterIP
      port: 80
      portName: atlantis
      targetPort: 4141
