apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubescape
  namespace: kubescape
spec:
  interval: 24h
  url: https://kubescape.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: kubescape
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: kubescape-operator
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: kubescape
      interval: 12h
  values:
    clusterName: "immanent-grove"
    capabilities:
      continuousScan: "enabled"
