apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubescape
  namespace: security
spec:
  interval: 24h
  url: https://kubescape.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: kubescape-operator
      version: "1.29.12"
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: security
      interval: 12h