apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: cilium
      version: "1.18.0-rc.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  values:
    ipam:
        mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
        capabilities:
            ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
            cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
    cgroup:
        autoMount:
            enabled: false
        hostRoot: "/sys/fs/cgroup"
    k8sServiceHost: localhost
    devices:
        - eth0
    k8sServicePort: 7445
    gatewayAPI:
        enabled: true
        enableAlpn: true
        enableAppProtocol: true
        secretsNamespace:
          sync: true
    l2announcements:
        enabled: true
    ingressController:
        enabled: true
        default: true
        loadbalancerMode: shared
        enforceHttps: false
    envoy:
        enabled: true
    hubble:
        peerService:
            clusterDomain: cluster.local
        relay:
            enabled: true
        ui:
            enabled: true
        tls:
            auto:
              enabled: true
              method: helm
              certValidityDuration: 2000
        metrics:
            enableOpenMetrics: true
            enabled:
            - dns
            - drop
            - tcp
