apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
    name: external
    namespace: kube-system
spec:
    interfaces :
    - "^eth[0-9]+"
    loadBalancerIPs: true
    nodeSelector:
        matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
