apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discsync-postgrest-api
spec:
  refreshInterval: "24h"
  target:
    name: discsync-postgrest-api
    creationPolicy: Owner
    template:
      data:
        api-key: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: discsync-postgrest-api-push
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: discsync-postgrest-api
  data:
    - match:
        secretKey: api-key
        remoteRef:
          remoteKey: discsync-postgrest-api
          property: api-key
