apiVersion: v2
name: minecraft
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.21.5"
dependencies:
- name: minecraft
  version: "4.26.0"
  repository: "https://itzg.github.io/minecraft-server-charts/"