vaultSecrets:
- name: "RESTIC_PASSWORD"
  path: "minecraft/restic-password"
- name: "RCON_PASSWORD"
  path: "minecraft/rcon-password"
- name: "RESTIC_REPOSITORY"
  path: "minecraft/restic-repository"
- name: "AWS_ACCESS_KEY_ID"
  path: "minecraft/aws-access-key-id"
- name: "AWS_SECRET_ACCESS_KEY"
  path: "minecraft/aws-secret-access-key"

minecraft:
  image:
    repository: itzg/minecraft-server
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      memory: 2048M
      cpu: 1500m

  # Define whether the server is run as a statefulset
  workloadAsStatefulSet: true
  strategyType: RollingUpdate
  podAnnotations:
    server: sexybabeycraft

  minecraftServer:
    eula: "TRUE"
    version: "1.21.5"
    type: "FABRIC"
    difficulty: hard
    whitelist: "Poopoopepe7, TestSubjectMoo, wauhn, ZinkIThink, facetiousfandago, papermustache, ncc_a, wpw_, SilverGorillaz, BenIsTheEpicest, Ragablaze"
    ops: "wauhn"
    icon: https://s3.vaughn.sh/cdn/server-icon.png
    maxPlayers: 10
    spawnProtection: 0
    gameMode: survival
    motd: "Every adventure is better with a friend!"
    worldSaveName: world
    memory: 1024M
    jvmXXOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
    serviceType: ClusterIP
    servicePort: 25565

    modrinth:
      projects:
        - c2me-fabric:VSNURh3q
        - ferrite-core:uXXizFIs
        - krypton:fQEb0iXm
        - lithium:gvQqBUqZ
        - modernfix:nmDcB62a
        - spark:l6YH9Als
        - tabtps:cUhi3iB2
        - mixintrace:sGmHWmeL
        - bluemap:swbUV1cr
        - bmarker:a8UoyV2h
        - image2map:13RpG7dA
        - noisium:KuNKN7d2
        - chunky:fALzjamp
      downloadDependencies: required
      allowedVersionType: default

    rcon:
      enabled: true
      withGeneratedPassword: false
      port: 25575
      existingSecret: rcon-password
      secretKey: value
      serviceType: ClusterIP

    tty: true

    query:
      enabled: false
      port: 25565

  persistence:
    annotations:
      server: sexybabeycraft
    dataDir:
      enabled: true
      Size: 64Gi
      accessModes:
        - ReadWriteOnce

  mcbackup:
    enabled: true

    image:
      repository: itzg/mc-backup
      tag: latest
      pullPolicy: IfNotPresent

    #  wait 2 minutes before starting
    initialDelay: 2m

    # ***set to 0 or smaller, script will run once and exit.  DO NOT SET TO 0 or smaller, this will cause K8s to kill your pod!***
    # backupInterval="1.5d" -> backup every one and a half days (36 hours)
    # backupInterval="2h 30m" -> backup every two and a half hours
    backupInterval: 2h

    # option lets you pause backups if no players are online.
    pauseIfNoPlayers: "false"

    # is set to a positive number, it'll delete old .tgz backup files from DEST_DIR. By default deletes backups older than a week.
    pruneBackupsDays: 7

    # Set to a negative value to retry indefinitely
    rconRetries: 5
    rconRetryInterval: 10s

    # is a comma-separated list of glob(3) patterns to exclude from backups. By default excludes all jar files (plugins, server files),
    # logs folder and cache (used by i.e. PaperMC server).
    excludes: "*.jar,cache,logs"

    # backup methods, see https://github.com/itzg/docker-mc-backup e.g. tar, rclone, restic, rsync
    backupMethod: restic
    destDir: /mc_backups
    linkLatest: "false"
    compressMethod: "gzip"
    zstdParameters: "-3 --long=25 --single-thread"
    resticAdditionalTags: "mc_backups"
    pruneResticRetention: "--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"

    extraEnv:
      RESTIC_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: restic-password
            key: value
      RESTIC_REPOSITORY:
        valueFrom:
          secretKeyRef:
            name: restic-repository
            key: value
      AWS_ACCESS_KEY_ID:
        valueFrom:
          secretKeyRef:
            name: aws-access-key-id
            key: value
      AWS_SECRET_ACCESS_KEY:
        valueFrom:
          secretKeyRef:
            name: aws-secret-access-key
            key: value

    resources:
      requests:
        memory: 512Mi
        cpu: 500m