---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-static-auth
spec:
  method: kubernetes
  mount: synkronized
  kubernetes:
    role: synkronized
    serviceAccount: vault-sa
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-restic-password
spec:
  type: kv-v2
  mount: kv
  path: minecraft/restic-password
  destination:
    name: restic-password
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-static-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-rcon-password
spec:
  type: kv-v2
  mount: kv
  path: minecraft/rcon-password
  destination:
    name: rcon-password
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-static-auth
