apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password-connect
  namespace: operators
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: operators
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: connect
      version: "2.0.2"
      sourceRef:
        kind: HelmRepository
        name: 1password-connect
        namespace: operators
      interval: 12h