apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-default-s3
spec:
  refreshPolicy: OnChange
  target:
    name: garage-default-s3
    creationPolicy: Owner
    template:
      data:
        bucket: garage-default
        endpoint-url: https://garage.internal.vw-ops.net
        region: garage
        access-key-id: "GK{{ .password | sha256sum | trunc 32 }}"
        secret-access-key: "{{ .password | sha256sum }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cluster-generator
