apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - admin-token.yaml
  - admin-service.yaml
  - credentials.yaml
  - pushsecret.yaml
  - repository.yaml
  - helmrelease.yaml
  - cdn-proxy.yaml
  - gateway.yaml
  - routes.yaml
  - public-ingress.yaml
configMapGenerator:
  - name: garage-cdn-proxy-config
    files:
      - Caddyfile
