apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-s3-public
  namespace: applications
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: cdn.vaughn.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-cdn-proxy
                port:
                  number: 80
    - host: s3.vaughn.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-cdn-proxy
                port:
                  number: 80
