apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: garage-default-s3-push
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: garage-default-s3
  data:
    - match:
        secretKey: bucket
        remoteRef:
          remoteKey: garage-default-s3
          property: bucket
    - match:
        secretKey: endpoint-url
        remoteRef:
          remoteKey: garage-default-s3
          property: endpoint-url
    - match:
        secretKey: region
        remoteRef:
          remoteKey: garage-default-s3
          property: region
    - match:
        secretKey: access-key-id
        remoteRef:
          remoteKey: garage-default-s3
          property: access-key-id
    - match:
        secretKey: secret-access-key
        remoteRef:
          remoteKey: garage-default-s3
          property: secret-access-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: garage-admin-token-push
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: garage-admin-token
  data:
    - match:
        secretKey: admin-token
        remoteRef:
          remoteKey: garage-admin-token
          property: admin-token
