---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin
        property: password