apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sbux-oracle-pg-app
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: sbux-oracle-pg-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "sbux-oracle-app"
        password: "{{ .password }}"
        uri: "postgresql://sbux-oracle-app:{{ .password | urlquery }}@grove-cluster-rw.applications.svc.cluster.local:5432/sbux-oracle"
        uri-pooler-rw: "postgresql://sbux-oracle-app:{{ .password | urlquery }}@grove-cluster-pooler-rw.applications.svc.cluster.local:5432/sbux-oracle"
        uri-pooler-ro: "postgresql://sbux-oracle-app:{{ .password | urlquery }}@grove-cluster-pooler-ro.applications.svc.cluster.local:5432/sbux-oracle"
  data:
    - secretKey: password
      remoteRef:
        key: sbux-oracle-pg-app
        property: password
