apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sbux-oracle-pg-app-push
spec:
  deletionPolicy: None
  refreshInterval: 24h
  secretStoreRefs:
    - name: 1password-sdk
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: cluster-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: sbux-oracle-pg-app
          property: password
