apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discsync-embeddings
spec:
  interval: 5m
  releaseName: discsync-embeddings
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: discsync-embeddings
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: discsync-embeddings
      interval: 5m
