apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: factorio-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: rcon-password
      remoteRef:
        key: factorio-rcon-password
        property: password
    - secretKey: game-password
      remoteRef:
        key: factorio-game-password
        property: password
    - secretKey: restic-password
      remoteRef:
        key: factorio-restic
        property: credential
    - secretKey: aws-access-key-id
      remoteRef:
        key: factorio-garage-role
        property: username
    - secretKey: aws-secret-access-key
      remoteRef:
        key: factorio-garage-role
        property: credential
