apiVersion: v1
kind: Service
metadata:
  name: factorio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: garage.internal.vw-ops.net
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: game
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-rcon
  annotations:
    external-dns.alpha.kubernetes.io/hostname: factorio-rcon.internal.vw-ops.net
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: rcon
