apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: game
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-rcon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: rcon
