apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crosstown-traffic
  namespace: crosstown-traffic
spec:
  interval: 24h
  url: oci://ghcr.io/vaughnw128/chart/crosstown-traffic
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crosstown-traffic
  namespace: crosstown-traffic
spec:
  interval: 30m
  chart:
    spec:
      chart: crosstown-traffic
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: crosstown-traffic
        namespace: crosstown-traffic
      interval: 12h
      valuesFiles:
        - "values.yaml"
