apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apicius-local-ca
  namespace: controllers
spec:
  commonName: "apicius.local"
  dnsNames:
    - "apicius.local"
    - "*.apicius.local"
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: local-self-signed-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: apicius-local