---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  namespace: operators
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: immanent-grove
      auth:
        serviceAccountSecretRef:
          name: 1password-sa-token
          key: token
          namespace: operators
  conditions:
  - namespaces:
      - "kube-system"
      - "operators"
      - "controllers"
      - "applications"