apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trust-manager
  namespace: controllers
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: trust-manager
      version: "v0.18.0"
      sourceRef:
        kind: HelmRepository
        name: trust-manager
        namespace: controllers
      interval: 12h
  values:
    app:
      trust:
        namespace: controllers