apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - noatime
    - nfsvers=4
  nfs:
    server: 10.0.0.3
    path: /mnt/pool/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
spec:
  storageClassName: ""
  volumeName: jellyfin-media
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
