apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: tetragon
      version: "1.29.12"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: security
      interval: 12h
  values:
    clusterName: "immanent-grove"
    capabilities:
      continuousScan: "enabled"
