apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: tetragon
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
