apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: controllers
spec:
  interval: 24h
  url: https://helm.strrl.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: controllers
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      version: "0.0.16"
      sourceRef:
        kind: HelmRepository
        name: cloudflare-tunnel-ingress-controller
        namespace: controllers
      interval: 12h
  values:
    cloudflare:
      secretRef:
         name: cloudflare-tunnel-controller
         apiTokenKey: token
         tunnelNameKey: name
         accountIDKey: account-id