apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: cloudflare-api-token/credential
