apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-controller
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: cloudflare-tunnel-controller/credential
  - secretKey: name
    remoteRef:
      key: cloudflare-tunnel-controller/name
  - secretKey: account-id
    remoteRef:
      key: cloudflare-tunnel-controller/account-id

