single-container:
    name: "pelican-panel"
    size: medium
    image: "ghcr.io/pelican-dev/panel:v1.0.0-beta18"

    gateway:
        public: false
        hostname: "panel.apicius.local"
        containerPort: 80

    vaultSecrets:
    - name: "APP_KEY"
      path: "pelican/app-key"
    env:
    - name: "TRUSTED_PROXIES"
      value: "*"
    - name: "APP_URL"
      value: "https://panel.apicius.local"
    - name: "APP_ENV"
      value: "production"
    - name: "ADMIN_EMAIL"
      value: "admin@vaughn.sh"
#    - name: "SKIP_CADDY"
#      value: "true"