name: Update Application Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
      app_repo:
        required: true
      image:
        required: true

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Wrap Input
        run: |
          echo "APP_REPO=${{ github.event.inputs.app_repo }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.app_repo }}" >> $GITHUB_ENV
          echo "DEPLOY_FILE_PATH=applications/${{ github.event.inputs.app_repo }}/values.yaml" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Update values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.single-container.image = "${{ env.IMAGE }}:${{ env.TAG_NAME }}"' '${{ env.DEPLOY_FILE_PATH }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update ${{ env.APP_REPO }} to ${{ env.TAG_NAME }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: app-release/${{ env.APP_REPO }}/${{ env.TAG_NAME }}
          title: 'Update ${{ env.APP_REPO }} to version ${{ env.TAG_NAME }}'
          labels: |
            automerge
            app-update
          body: |
            This PR was automatically created.
            Please review and merge to deploy.