name: Update Application Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
      app_repo:
        required: true
      image:
        required: true

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Wrap Input
        run: |
          echo "APP_REPO=${{ github.event.inputs.app_repo }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${{ github.event.repository.owner.name }}/${{ github.event.inputs.app_repo }}" >> $GITHUB_ENV
          echo "DEPLOY_FILE_PATH=applications/${{ github.event.inputs.app_repo }}/values.yaml" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{ env.DEPLOY_FILE_PATH }}
          propertyPath: "single\-container.image"
          value: ${{ env.IMAGE }}
          branch: ${{ env.APP_REPO }}/${{ env.TAG_NAME }}
          createPR: true
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'