name: Automerge
on:
  pull_request:
    types:
      - opened
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
         MERGE_FILTER_AUTHOR: "vaughnw128"
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"