name: Flux Diff

on:
  pull_request:
     branches:
          - 'main'

jobs:
  diff:
    name: Flux Local Diff
    runs-on: ubuntu-latest
    steps:
     - name: Setup Flux CLI
       uses: fluxcd/flux2/action@v2.2.3
     - uses: allenporter/flux-local/action/diff@4.3.1
       id: diff
       with:
         live-branch: main
         path: cluster
         resource: helmrelease
     - name: PR Comments
       uses: mshick/add-pr-comment@v2
       if: ${{ steps.diff.outputs.diff != '' }}
       with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         message-failure: Unable to post diff
         message: |
           `````diff
           ${{ steps.diff.outputs.diff }}
           `
