name: Flux Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  manifests:
    name: Verify Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Validate manifests
        run: bash ./scripts/validate-flux.sh
  flux-local:
    name: Flux Local Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.2.2
      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          mv kustomize $HOME/.local/bin/kustomize
      - uses: allenporter/flux-local/action/test@4.3.1
        with:
          path: ./cluster/
          enable-helm: true
